/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos/': RouteRecordInfo<
      '/demos/',
      '/demos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/信号分析与处理': RouteRecordInfo<
      '/posts/信号分析与处理',
      '/posts/%E4%BF%A1%E5%8F%B7%E5%88%86%E6%9E%90%E4%B8%8E%E5%A4%84%E7%90%86',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/学术规范与论文写作': RouteRecordInfo<
      '/posts/学术规范与论文写作',
      '/posts/%E5%AD%A6%E6%9C%AF%E8%A7%84%E8%8C%83%E4%B8%8E%E8%AE%BA%E6%96%87%E5%86%99%E4%BD%9C',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/工程伦理': RouteRecordInfo<
      '/posts/工程伦理',
      '/posts/%E5%B7%A5%E7%A8%8B%E4%BC%A6%E7%90%86',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/矩阵论期末复习笔记': RouteRecordInfo<
      '/posts/矩阵论期末复习笔记',
      '/posts/%E7%9F%A9%E9%98%B5%E8%AE%BA%E6%9C%9F%E6%9C%AB%E5%A4%8D%E4%B9%A0%E7%AC%94%E8%AE%B0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/科学道德与学风': RouteRecordInfo<
      '/posts/科学道德与学风',
      '/posts/%E7%A7%91%E5%AD%A6%E9%81%93%E5%BE%B7%E4%B8%8E%E5%AD%A6%E9%A3%8E',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/英语单词': RouteRecordInfo<
      '/posts/英语单词',
      '/posts/%E8%8B%B1%E8%AF%AD%E5%8D%95%E8%AF%8D',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Ai-Thinker环境搭建': RouteRecordInfo<
      '/posts/Ai-Thinker环境搭建',
      '/posts/Ai-Thinker%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/AI Vocabulary': RouteRecordInfo<
      '/posts/AI Vocabulary',
      '/posts/AI%20Vocabulary',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/alist记录': RouteRecordInfo<
      '/posts/alist记录',
      '/posts/alist%E8%AE%B0%E5%BD%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CCG': RouteRecordInfo<
      '/posts/CCG',
      '/posts/CCG',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CCG with CC-Switch': RouteRecordInfo<
      '/posts/CCG with CC-Switch',
      '/posts/CCG%20with%20CC-Switch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Claude&Codex配置': RouteRecordInfo<
      '/posts/Claude&Codex配置',
      '/posts/Claude&Codex%E9%85%8D%E7%BD%AE',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CLIProxyAPI搭建与使用': RouteRecordInfo<
      '/posts/CLIProxyAPI搭建与使用',
      '/posts/CLIProxyAPI%E6%90%AD%E5%BB%BA%E4%B8%8E%E4%BD%BF%E7%94%A8',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CSTC&OSCA': RouteRecordInfo<
      '/posts/CSTC&OSCA',
      '/posts/CSTC&OSCA',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/E2000D测试': RouteRecordInfo<
      '/posts/E2000D测试',
      '/posts/E2000D%E6%B5%8B%E8%AF%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ffmpeg常用教程': RouteRecordInfo<
      '/posts/ffmpeg常用教程',
      '/posts/ffmpeg%E5%B8%B8%E7%94%A8%E6%95%99%E7%A8%8B',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/GCMP': RouteRecordInfo<
      '/posts/GCMP',
      '/posts/GCMP',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/GCMP插件介绍': RouteRecordInfo<
      '/posts/GCMP插件介绍',
      '/posts/GCMP%E6%8F%92%E4%BB%B6%E4%BB%8B%E7%BB%8D',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/HDLBits刷题': RouteRecordInfo<
      '/posts/HDLBits刷题',
      '/posts/HDLBits%E5%88%B7%E9%A2%98',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hello-valaxy': RouteRecordInfo<
      '/posts/hello-valaxy',
      '/posts/hello-valaxy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Linux记录': RouteRecordInfo<
      '/posts/Linux记录',
      '/posts/Linux%E8%AE%B0%E5%BD%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/openclaw-wsl-installation': RouteRecordInfo<
      '/posts/openclaw-wsl-installation',
      '/posts/openclaw-wsl-installation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/OpenClaw搭建与使用': RouteRecordInfo<
      '/posts/OpenClaw搭建与使用',
      '/posts/OpenClaw%E6%90%AD%E5%BB%BA%E4%B8%8E%E4%BD%BF%E7%94%A8',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Prompt记录': RouteRecordInfo<
      '/posts/Prompt记录',
      '/posts/Prompt%E8%AE%B0%E5%BD%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Skills记录': RouteRecordInfo<
      '/posts/Skills记录',
      '/posts/Skills%E8%AE%B0%E5%BD%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/STM32的PID算法': RouteRecordInfo<
      '/posts/STM32的PID算法',
      '/posts/STM32%E7%9A%84PID%E7%AE%97%E6%B3%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/T113-i记录': RouteRecordInfo<
      '/posts/T113-i记录',
      '/posts/T113-i%E8%AE%B0%E5%BD%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Unify Chat Provider for Copilot': RouteRecordInfo<
      '/posts/Unify Chat Provider for Copilot',
      '/posts/Unify%20Chat%20Provider%20for%20Copilot',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/WSL记录': RouteRecordInfo<
      '/posts/WSL记录',
      '/posts/WSL%E8%AE%B0%E5%BD%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ZYNQ': RouteRecordInfo<
      '/posts/ZYNQ',
      '/posts/ZYNQ',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/websites/': RouteRecordInfo<
      '/websites/',
      '/websites',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/demos/index.md': {
      routes:
        | '/demos/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/信号分析与处理.md': {
      routes:
        | '/posts/信号分析与处理'
      views:
        | never
    }
    'pages/posts/学术规范与论文写作.md': {
      routes:
        | '/posts/学术规范与论文写作'
      views:
        | never
    }
    'pages/posts/工程伦理.md': {
      routes:
        | '/posts/工程伦理'
      views:
        | never
    }
    'pages/posts/矩阵论期末复习笔记.md': {
      routes:
        | '/posts/矩阵论期末复习笔记'
      views:
        | never
    }
    'pages/posts/科学道德与学风.md': {
      routes:
        | '/posts/科学道德与学风'
      views:
        | never
    }
    'pages/posts/英语单词.md': {
      routes:
        | '/posts/英语单词'
      views:
        | never
    }
    'pages/posts/Ai-Thinker环境搭建.md': {
      routes:
        | '/posts/Ai-Thinker环境搭建'
      views:
        | never
    }
    'pages/posts/AI Vocabulary.md': {
      routes:
        | '/posts/AI Vocabulary'
      views:
        | never
    }
    'pages/posts/alist记录.md': {
      routes:
        | '/posts/alist记录'
      views:
        | never
    }
    'pages/posts/CCG.md': {
      routes:
        | '/posts/CCG'
      views:
        | never
    }
    'pages/posts/CCG with CC-Switch.md': {
      routes:
        | '/posts/CCG with CC-Switch'
      views:
        | never
    }
    'pages/posts/Claude&Codex配置.md': {
      routes:
        | '/posts/Claude&Codex配置'
      views:
        | never
    }
    'pages/posts/CLIProxyAPI搭建与使用.md': {
      routes:
        | '/posts/CLIProxyAPI搭建与使用'
      views:
        | never
    }
    'pages/posts/CSTC&OSCA.md': {
      routes:
        | '/posts/CSTC&OSCA'
      views:
        | never
    }
    'pages/posts/E2000D测试.md': {
      routes:
        | '/posts/E2000D测试'
      views:
        | never
    }
    'pages/posts/ffmpeg常用教程.md': {
      routes:
        | '/posts/ffmpeg常用教程'
      views:
        | never
    }
    'pages/posts/GCMP.md': {
      routes:
        | '/posts/GCMP'
      views:
        | never
    }
    'pages/posts/GCMP插件介绍.md': {
      routes:
        | '/posts/GCMP插件介绍'
      views:
        | never
    }
    'pages/posts/HDLBits刷题.md': {
      routes:
        | '/posts/HDLBits刷题'
      views:
        | never
    }
    'pages/posts/hello-valaxy.md': {
      routes:
        | '/posts/hello-valaxy'
      views:
        | never
    }
    'pages/posts/Linux记录.md': {
      routes:
        | '/posts/Linux记录'
      views:
        | never
    }
    'pages/posts/openclaw-wsl-installation.md': {
      routes:
        | '/posts/openclaw-wsl-installation'
      views:
        | never
    }
    'pages/posts/OpenClaw搭建与使用.md': {
      routes:
        | '/posts/OpenClaw搭建与使用'
      views:
        | never
    }
    'pages/posts/Prompt记录.md': {
      routes:
        | '/posts/Prompt记录'
      views:
        | never
    }
    'pages/posts/Skills记录.md': {
      routes:
        | '/posts/Skills记录'
      views:
        | never
    }
    'pages/posts/STM32的PID算法.md': {
      routes:
        | '/posts/STM32的PID算法'
      views:
        | never
    }
    'pages/posts/T113-i记录.md': {
      routes:
        | '/posts/T113-i记录'
      views:
        | never
    }
    'pages/posts/Unify Chat Provider for Copilot.md': {
      routes:
        | '/posts/Unify Chat Provider for Copilot'
      views:
        | never
    }
    'pages/posts/WSL记录.md': {
      routes:
        | '/posts/WSL记录'
      views:
        | never
    }
    'pages/posts/ZYNQ.md': {
      routes:
        | '/posts/ZYNQ'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
    'pages/websites/index.md': {
      routes:
        | '/websites/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
