/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/Ai-Thinker环境搭建': RouteRecordInfo<'/posts/Ai-Thinker环境搭建', '/posts/Ai-Thinker环境搭建', Record<never, never>, Record<never, never>>,
    '/posts/alist记录': RouteRecordInfo<'/posts/alist记录', '/posts/alist记录', Record<never, never>, Record<never, never>>,
    '/posts/E2000D测试': RouteRecordInfo<'/posts/E2000D测试', '/posts/E2000D测试', Record<never, never>, Record<never, never>>,
    '/posts/ffmpeg常用教程': RouteRecordInfo<'/posts/ffmpeg常用教程', '/posts/ffmpeg常用教程', Record<never, never>, Record<never, never>>,
    '/posts/HDLBits刷题': RouteRecordInfo<'/posts/HDLBits刷题', '/posts/HDLBits刷题', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/Linux记录': RouteRecordInfo<'/posts/Linux记录', '/posts/Linux记录', Record<never, never>, Record<never, never>>,
    '/posts/STM32的PID算法': RouteRecordInfo<'/posts/STM32的PID算法', '/posts/STM32的PID算法', Record<never, never>, Record<never, never>>,
    '/posts/T113-i记录': RouteRecordInfo<'/posts/T113-i记录', '/posts/T113-i记录', Record<never, never>, Record<never, never>>,
    '/posts/ZYNQ': RouteRecordInfo<'/posts/ZYNQ', '/posts/ZYNQ', Record<never, never>, Record<never, never>>,
    '/posts/学术规范与论文写作': RouteRecordInfo<'/posts/学术规范与论文写作', '/posts/学术规范与论文写作', Record<never, never>, Record<never, never>>,
    '/posts/工程伦理': RouteRecordInfo<'/posts/工程伦理', '/posts/工程伦理', Record<never, never>, Record<never, never>>,
    '/posts/科学道德与学风': RouteRecordInfo<'/posts/科学道德与学风', '/posts/科学道德与学风', Record<never, never>, Record<never, never>>,
    '/posts/英语单词': RouteRecordInfo<'/posts/英语单词', '/posts/英语单词', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.26.6_vue@3.5.21_typescript@5.9.2_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes: '/'
      views: never
    }
    'node_modules/.pnpm/valaxy@0.26.6_@babel+parser_066905c32c0987c906696cd124c50e27/node_modules/valaxy/client/pages/[...path].vue': {
      routes: '/[...path]'
      views: never
    }
    'pages/404.md': {
      routes: '/404'
      views: never
    }
    'pages/about/index.md': {
      routes: '/about/'
      views: never
    }
    'pages/about/site.md': {
      routes: '/about/site'
      views: never
    }
    'pages/archives/index.md': {
      routes: '/archives/'
      views: never
    }
    'pages/categories/index.md': {
      routes: '/categories/'
      views: never
    }
    'pages/links/index.md': {
      routes: '/links/'
      views: never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.6_vue@3.5.21_typescript@5.9.2_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes: '/page/[page]'
      views: never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.6_vue@3.5.21_typescript@5.9.2_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes: '/posts/'
      views: never
    }
    'pages/posts/Ai-Thinker环境搭建.md': {
      routes: '/posts/Ai-Thinker环境搭建'
      views: never
    }
    'pages/posts/alist记录.md': {
      routes: '/posts/alist记录'
      views: never
    }
    'pages/posts/E2000D测试.md': {
      routes: '/posts/E2000D测试'
      views: never
    }
    'pages/posts/ffmpeg常用教程.md': {
      routes: '/posts/ffmpeg常用教程'
      views: never
    }
    'pages/posts/HDLBits刷题.md': {
      routes: '/posts/HDLBits刷题'
      views: never
    }
    'pages/posts/hello-valaxy.md': {
      routes: '/posts/hello-valaxy'
      views: never
    }
    'pages/posts/Linux记录.md': {
      routes: '/posts/Linux记录'
      views: never
    }
    'pages/posts/STM32的PID算法.md': {
      routes: '/posts/STM32的PID算法'
      views: never
    }
    'pages/posts/T113-i记录.md': {
      routes: '/posts/T113-i记录'
      views: never
    }
    'pages/posts/ZYNQ.md': {
      routes: '/posts/ZYNQ'
      views: never
    }
    'pages/posts/学术规范与论文写作.md': {
      routes: '/posts/学术规范与论文写作'
      views: never
    }
    'pages/posts/工程伦理.md': {
      routes: '/posts/工程伦理'
      views: never
    }
    'pages/posts/科学道德与学风.md': {
      routes: '/posts/科学道德与学风'
      views: never
    }
    'pages/posts/英语单词.md': {
      routes: '/posts/英语单词'
      views: never
    }
    'pages/tags/index.md': {
      routes: '/tags/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
